main:
	gcc -Wall -o main main.c -lpthread -lm
	./main 1 mountain.pgm filter3 output.pgm
	./main 2 mountain.pgm filter3 output.pgm
	./main 4 mountain.pgm filter3 output.pgm
	./main 8 mountain.pgm filter3 output.pgm
	./main 1 mountain.pgm filter39 output.pgm
	./main 2 mountain.pgm filter39 output.pgm
	./main 4 mountain.pgm filter39 output.pgm
	./main 8 mountain.pgm filter39 output.pgm

clean:
	rm main output.pgm 

	
